# Generated by Django 3.2.4 on 2023-05-13 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobExecuteHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_biz_id', models.IntegerField(verbose_name='业务ID')),
                ('job_plan_id', models.IntegerField(verbose_name='作业方案ID')),
                ('job_instance_id', models.BigIntegerField(verbose_name='作业实例ID')),
                ('job_instance_name', models.CharField(max_length=255, verbose_name='作业实例名称')),
                ('is_finished', models.BooleanField(default=False, verbose_name='作业是否结束')),
                ('status', models.IntegerField(choices=[(1, '未执行'), (2, '正在执行'), (3, '执行成功'), (4, '执行失败'), (5, '跳过'), (6, '忽略错误'), (7, '等待用户'), (8, '手动结束'), (9, '状态异常'), (10, '步骤强制终止中'), (11, '步骤强制终止成功')], default=1, verbose_name='作业执行状态')),
                ('create_time', models.BigIntegerField(null=True, verbose_name='作业创建时间(毫秒)')),
                ('start_time', models.BigIntegerField(null=True, verbose_name='开始执行时间(毫秒)')),
                ('end_time', models.BigIntegerField(null=True, verbose_name='执行结束时间(毫秒)')),
                ('total_time', models.IntegerField(null=True, verbose_name='总耗时(毫秒)')),
            ],
        ),
    ]
